name: Deploy Action
description: Sobird's Deploy Action
author: sobird
branding:
  icon: 'crosshair' # 使用的是Feather的图标
  color: 'gray-dark' # 图标颜色
# Define your inputs here.
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World
  milliseconds:
    description: Your input description here
    required: true
    defalut: 1000
  host:
    description: remote host
    required: true
  port:
    description: remote host port
    default: 22
  username:
    description: ssh username
    required: true
  password:
    description: ssh password
    required: true
  source:
    description: scp file list
    required: true
  target:
    description: target path on the remote server
    required: true

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js
